name: Daily Scrape
on:
  schedule:
    - cron: "0 3 * * *" # 3 AM UTC daily
  workflow_dispatch: # Allows manual triggering
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -la
      - name: Check Python version
        run: python --version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: |
          set -x
          python ./scripts/extract_7days_events_urls_by_promotion.py